# FROM vements/substitute-server:latest
FROM vements/substitute-server:latest AS sub

FROM --platform=$BUILDPLATFORM alpine:3.18 AS build
ARG BUILDPLATFORM


RUN apk add --no-cache \
    go \
    python3 \
    py3-pip 

WORKDIR /app
COPY --from=sub /app/subserver /app/subserver
COPY --from=sub /app/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY go.* /app/
COPY cmd /app/cmd
COPY vements /app/vements
RUN go mod tidy -go=1.20

ENV PORT=9000

ENTRYPOINT python -m subserver & \
    cd /app/vements && \
    go test -v
